apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kokabie.li.kokabie.li/v1alpha1",
          "kind": "DataInterface",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kokabieli-operator",
              "app.kubernetes.io/instance": "datainterface-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "datainterface",
              "app.kubernetes.io/part-of": "kokabieli-operator"
            },
            "name": "datainterface-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "kokabie.li.kokabie.li/v1alpha1",
          "kind": "DataProcess",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kokabieli-operator",
              "app.kubernetes.io/instance": "dataprocess-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dataprocess",
              "app.kubernetes.io/part-of": "kokabieli-operator"
            },
            "name": "dataprocess-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-10-15T13:15:50Z"
    operators.operatorframework.io/builder: operator-sdk-unknown
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: kokabieli-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DataInterface is the Schema for the datainterfaces API
      displayName: Data Interface
      kind: DataInterface
      name: datainterfaces.kokabie.li.kokabie.li
      version: v1alpha1
    - description: DataProcess is the Schema for the dataprocesses API
      displayName: Data Process
      kind: DataProcess
      name: dataprocesses.kokabie.li.kokabie.li
      version: v1alpha1
  description: allows to automatically build a constellation of your dataprocessing
  displayName: kokabieli
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - datainterfaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - datainterfaces/finalizers
          verbs:
          - update
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - datainterfaces/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - dataprocesses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - dataprocesses/finalizers
          verbs:
          - update
        - apiGroups:
          - kokabie.li.kokabie.li
          resources:
          - dataprocesses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kokabieli-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: kokabieli-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: kokabieli-operator
          control-plane: controller-manager
        name: kokabieli-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kokabieli-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kokabieli-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - data
  - processing
  - kokabieli
  - constellation
  - flow
  links:
  - name: Kokabieli Operator
    url: https://kokabieli-operator.domain
  maintainers:
  - email: f@schr.ag
    name: Florian Schrag
  maturity: alpha
  provider:
    name: kokabieli
    url: github.com/kokabieli
  version: 0.0.1
