apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kokabieli-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Constellation is the Schema for the constellations API
      displayName: Constellation
      kind: Constellation
      name: constellations.kokabie.li.kokabie.li
      statusDescriptors:
      - description: Conditions store the status conditions of the constellation
        displayName: Conditions
        path: conditions
      - description: ConstellationResult is the result of the constellation
        displayName: Constellation Result
        path: constellationResult
      version: v1alpha1
    - description: DataInterface is the Schema for the datainterfaces API
      displayName: Data Interface
      kind: DataInterface
      name: datainterfaces.kokabie.li.kokabie.li
      statusDescriptors:
      - description: Conditions store the status conditions of the data interface
        displayName: Conditions
        path: conditions
      - description: UsedInDataProcesses is a list of data processes that use this
          data interface
        displayName: Used In Data Processes
        path: usedInDataProcesses
      - description: UsedReferences is the generated name of the data interface
        displayName: Used Reference
        path: usedReference
      version: v1alpha1
    - description: DataProcess is the Schema for the dataprocesses API
      displayName: Data Process
      kind: DataProcess
      name: dataprocesses.kokabie.li.kokabie.li
      statusDescriptors:
      - description: Conditions store the status conditions of the data process
        displayName: Conditions
        path: conditions
      - description: Loaded is true if the data process is loaded into the system
        displayName: Loaded
        path: loaded
      - description: 'Important: Run "make" to regenerate code after modifying this
          file'
        displayName: Missing Data Interfaces
        path: missingDataInterfaces
      version: v1alpha1
  description: allows to automatically build a constellation of your dataprocessing
  displayName: kokabieli
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - data
  - processing
  - kokabieli
  - constellation
  - flow
  links:
  - name: Kokabieli Operator
    url: https://kokabieli-operator.domain
  maintainers:
  - email: f@schr.ag
    name: Florian Schrag
  maturity: alpha
  provider:
    name: kokabieli
    url: github.com/kokabieli
  version: 0.0.0
