apiVersion: kokabie.li/v1alpha1
kind: DataProcess
metadata:
  labels:
    app.kubernetes.io/name: dataprocess
    app.kubernetes.io/instance: dataprocess-sample
    app.kubernetes.io/part-of: kokabieli-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kokabieli-operator
  name: dataprocess-sample
spec:
    name: dataprocess-sample
    type: dataprocess
    description: "This is a sample DataProcess"
    inputs:
        - reference: "datainterface-sample"
          trigger: true
          description: "This is a sample input"
    outputs:
        - reference: "datainterface-sample"
          description: "This is a sample output"
          trigger: true
