apiVersion: kokabie.li.kokabie.li/v1alpha1
kind: DataInterface
metadata:
  labels:
    app.kubernetes.io/name: datainterface
    app.kubernetes.io/instance: datainterface-sample
    app.kubernetes.io/part-of: kokabieli-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kokabieli-operator
  name: datainterface-sample
spec:
  # TODO(user): Add fields here
